<?php

namespace Tests\Feature;

use Database\Seeders\RolesSeeder;
use Database\Seeders\RoleUserSeeder;
use Database\Seeders\UsersTableSeeder;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use App\Models\User;
use App\Models\chores;
use Database\Seeders\ChoresSeeder;
use Tests\TestCase;

class ChoresControllerTest extends TestCase
{
    use DatabaseMigrations;
    
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_chore_can_be_created()
    {
        $choreData = [
            'chore' => 'Test chore',
            'pointvalue' => 10
        ];

        $this->seed(UsersTableSeeder::class);
        $this->seed(RolesSeeder::class);
        $this->seed(RoleUserSeeder::class);

        // User is generated by the seeder
        $user = User::find(1);
        
        $response = $this->actingAs($user)->postJson('/api/chores', $choreData);

        $response->assertStatus(201);
    }

    /**
     * @return void
     */
    public function test_chores_can_be_fetched()
    {
        $this->seed(UsersTableSeeder::class);
        $this->seed(RolesSeeder::class);
        $this->seed(RoleUserSeeder::class);
        $this->seed(ChoresSeeder::class);

        $user = User::find(1);

        $response = $this->actingAs($user)->getJson('/api/chores');

        $response->assertStatus(200);

        $response->assertJsonCount(5);        
    }

    /**
     * @return void
     */
    public function test_a_chore_can_be_updated()
    {        
        $this->seed(UsersTableSeeder::class);
        $this->seed(RolesSeeder::class);
        $this->seed(RoleUserSeeder::class);
        $this->seed(ChoresSeeder::class);

        $user = User::find(1);

        $chore = Chores::find(1);
        $chore->chore = $chore->chore . "Updated";
        $chore->pointvalue = 15;

        $response = $this->actingAs($user)->putJson('/api/chores/'.$chore->id, $chore->toArray());

        $response->assertStatus(200);
    }
    
    /**
     * @return void
     */
    public function test_a_chore_can_be_deleted()
    {        
        $this->seed(UsersTableSeeder::class);
        $this->seed(RolesSeeder::class);
        $this->seed(RoleUserSeeder::class);
        $this->seed(ChoresSeeder::class);

        $user = User::find(1);

        $chore = Chores::find(1);

        $response = $this->actingAs($user)->deleteJson('/api/chores/'.$chore->id);

        $response->assertStatus(200);
    }
}
