<?php

namespace Tests\Feature;

use Database\Seeders\RolesSeeder;
use Database\Seeders\RoleUserSeeder;
use Database\Seeders\UsersTableSeeder;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use App\Models\User;
use Tests\TestCase;

class ChoresControllerTest extends TestCase
{
    use DatabaseMigrations;
    
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_chore_can_be_created()
    {
        $choreData = [
            'chore' => 'Test chore',
            'pointvalue' => 10
        ];

        $this->seed(UsersTableSeeder::class);
        $this->seed(RolesSeeder::class);
        $this->seed(RoleUserSeeder::class);

        // User is generated by the seeder
        $user = User::find(1);
        
        $response = $this->actingAs($user)->postJson('/api/chores', $choreData);

        $response->assertStatus(201);
    }
}
