<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\chores;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ChoresControllerTest extends TestCase
{
    use RefreshDatabase;
    
    /**
     * Test that a chore can be created.
     *
     * @return void
     */
    public function test_chore_can_be_created()
    {
        $choreData = [
            'chore' => 'Test chore',
            'pointvalue' => 10
        ];

        // User is generated by the seeder
        $user = User::find(1);
        
        $response = $this->actingAs($user)->postJson('/api/chores', $choreData);

        $response->assertStatus(201);
    }

    /**
     * Test that chores can be fetched
     * 
     * @return void
     */
    public function test_chores_can_be_fetched()
    {
        $user = User::find(1);

        $response = $this->actingAs($user)->getJson('/api/chores');

        $response->assertStatus(200);

        $response->assertJsonCount(5);        
    }

    /**
     * Test that a chore can be updated
     * 
     * @return void
     */
    public function test_a_chore_can_be_updated()
    {
        $user = User::find(1);

        $chore = Chores::find(1);
        $chore->chore = $chore->chore . "Updated";
        $chore->pointvalue = 15;

        $response = $this->actingAs($user)->putJson('/api/chores/'.$chore->id, $chore->toArray());

        $response->assertStatus(200);
    }
    
    /**
     * Test that a chore can be deleted
     * 
     * @return void
     */
    public function test_a_chore_can_be_deleted()
    {
        $user = User::find(1);

        $chore = Chores::find(1);

        $response = $this->actingAs($user)->deleteJson('/api/chores/'.$chore->id);

        $response->assertStatus(200);
    }
}
