<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\User;
use App\Models\Reward;
use Illuminate\Http\UploadedFile;
use Database\Seeders\RolesSeeder;
use Database\Seeders\RoleUserSeeder;
use Database\Seeders\UsersTableSeeder;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\Mailer\Transport\Dsn;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class RewardControllerTest extends TestCase
{
    use DatabaseMigrations;

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_reward_can_be_created()
    {
        $this->seed(UsersTableSeeder::class);
        $this->seed(RolesSeeder::class);
        $this->seed(RoleUserSeeder::class);
        
        Storage::fake('file');

        $file = UploadedFile::fake()->image('test.jpg');
        
        $rewardData = [
            'reward' => 'Test Reward',
            'pointvalue' => 10,
            'file' => $file
        ];

        // User is generated by the seeder
        $user = User::find(1);
        
        $response = $this->actingAs($user)->postJson('/api/rewards', $rewardData);

        $response->assertStatus(200);
    }
}
